[package]
name = "libmdns"
version = "0.5.0"
authors = ["Will Stott <willstott101+libmdns@gmail.com>"]

description = "mDNS Responder library for building discoverable LAN services in Rust"
repository = "https://github.com/librespot-org/libmdns"
readme = "README.md"
license = "MIT"
edition = "2018"

[dependencies]
dns-message-parser = "0.4"
if-addrs = "0.6"
hostname = "0.3"
log = "0.4"
multimap = "0.8"
rand = "0.7"
futures-util = "0.3"
tokio = { version = "0.3.4", features = ["sync","net","stream","rt"] }
socket2 = { version = "0.3.16", features = ["reuseport"] }

[dev-dependencies]
env_logger =  { version = "0.7", default-features = false, features = ["termcolor","humantime","atty"] } 
